# On pushing to kubernetes branch, build and push docker images with tags
# - latest
# - shorted SHA

name: latest

on:
  push:
    branches:
      - kubernetes

jobs:

  docker_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Get short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      -
        name: Store short SHA as environment variable
        run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      -
        # TODO: push to non-personal repository
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            bengig/jupyterhub-fileserver-api:kubernetes
            bengig/jupyterhub-fileserver-api:${{ env.SHA }}
